export const formTemplates = [
  {
    title: "Service Request",
    id: crypto.randomUUID(),
    description: "Request form for professional services and consultations.",
    category: "Business Forms",
    tags: ["Services", "Business", "Request"],
    buttonText: "Submit Request",
    formConfig: [
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Full Name",
        required: true,
        placeholder: "John Doe",
      },
      {
        id: crypto.randomUUID(),
        type: "email",
        label: "Email",
        required: true,
        placeholder: "john@example.com",
      },
      {
        id: crypto.randomUUID(),
        type: "select",
        label: "Service Type",
        required: true,
        options: [
          { label: "Consultation", value: "consultation" },
          { label: "Technical Support", value: "technical" },
          { label: "Quote Request", value: "quote" },
          { label: "Other Services", value: "other" },
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "radio-group",
        label: "Urgency Level",
        required: true,
        options: [
          { label: "High Priority", value: "high" },
          { label: "Medium Priority", value: "medium" },
          { label: "Low Priority", value: "low" },
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "textarea",
        label: "Service Details",
        required: true,
        placeholder: "Please describe your service needs...",
      },
    ],
  },

  {
    title: "Customer Feedback",
    id: crypto.randomUUID(),
    description:
      "Comprehensive feedback form for product or service evaluation.",
    category: "Survey Forms",
    tags: ["Feedback", "Survey", "Customer"],
    buttonText: "Submit Feedback",
    formConfig: [
      {
        id: crypto.randomUUID(),
        type: "radio-group",
        label: "Overall Satisfaction",
        required: true,
        options: [
          { label: "Very Satisfied", value: "5" },
          { label: "Satisfied", value: "4" },
          { label: "Neutral", value: "3" },
          { label: "Dissatisfied", value: "2" },
          { label: "Very Dissatisfied", value: "1" },
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "checkbox-group",
        label: "Areas to Improve",
        required: true,
        options: [
          { label: "Product Quality", value: "quality" },
          { label: "Customer Service", value: "service" },
          { label: "Price", value: "price" },
          { label: "User Experience", value: "ux" },
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "textarea",
        label: "Additional Comments",
        required: false,
        placeholder: "Please share your thoughts...",
      },
    ],
  },

  {
    title: "Event Registration",
    description:
      "Complete event registration form for conferences and workshops.",
    category: "Registration Forms",
    tags: ["Events", "Registration", "Booking"],
    buttonText: "Register Now",
    formConfig: [
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Full Name",
        required: true,
        placeholder: "John Doe",
      },
      {
        id: crypto.randomUUID(),
        type: "email",
        label: "Email",
        required: true,
        placeholder: "john@example.com",
      },
      {
        id: crypto.randomUUID(),
        type: "select",
        label: "Event Type",
        required: true,
        options: [
          { label: "Conference", value: "conference" },
          { label: "Workshop", value: "workshop" },
          { label: "Webinar", value: "webinar" },
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "checkbox-group",
        label: "Sessions",
        required: true,
        options: [
          { label: "Morning Session", value: "morning" },
          { label: "Afternoon Session", value: "afternoon" },
          { label: "Evening Session", value: "evening" },
        ],
      },
    ],
  },

  {
    title: "Job Application",
    description: "Comprehensive job application form for candidates.",
    category: "Application Forms",
    tags: ["Employment", "Career", "Jobs"],
    buttonText: "Submit Application",
    formConfig: [
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Full Name",
        required: true,
        placeholder: "John Doe",
      },
      {
        id: crypto.randomUUID(),
        type: "email",
        label: "Email",
        required: true,
        placeholder: "john@example.com",
      },
      {
        id: crypto.randomUUID(),
        type: "number",
        label: "Years of Experience",
        required: true,
        placeholder: "5",
      },
      {
        id: crypto.randomUUID(),
        type: "select",
        label: "Position",
        required: true,
        options: [
          { label: "Software Developer", value: "developer" },
          { label: "Designer", value: "designer" },
          { label: "Product Manager", value: "pm" },
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "checkbox-group",
        label: "Skills",
        required: true,
        options: [
          { label: "JavaScript", value: "js" },
          { label: "Python", value: "python" },
          { label: "React", value: "react" },
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "textarea",
        label: "Cover Letter",
        required: true,
        placeholder: "Tell us about yourself...",
      },
    ],
  },
  {
    title: "Medical Appointment",
    id: crypto.randomUUID(),
    description: "Schedule an appointment with a healthcare provider.",
    category: "Healthcare Forms",
    tags: ["Medical", "Appointment", "Doctor"],
    buttonText: "Book Appointment",
    formConfig: [
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Full Name",
        required: true,
        placeholder: "John Doe",
      },
      {
        id: crypto.randomUUID(),
        type: "email",
        label: "Email",
        required: true,
        placeholder: "john@example.com",
      },
      {
        id: crypto.randomUUID(),
        type: "number",
        label: "Phone Number",
        required: true,
        placeholder: "1234567890",
      },
      {
        id: crypto.randomUUID(),
        type: "select",
        label: "Preferred Doctor",
        required: true,
        options: [
          { label: "Dr. Smith", value: "smith" },
          { label: "Dr. Jane", value: "jane" },
          { label: "Dr. Lee", value: "lee" },
        ],
      },

      {
        id: crypto.randomUUID(),
        type: "textarea",
        label: "Symptoms",
        required: true,
        placeholder: "Describe your symptoms...",
      },
    ],
  },
  {
    title: "Loan Application",
    id: crypto.randomUUID(),
    description: "Apply for a personal or business loan.",
    category: "Financial Forms",
    tags: ["Loan", "Finance", "Application"],
    buttonText: "Apply for Loan",
    formConfig: [
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Full Name",
        required: true,
        placeholder: "John Doe",
      },
      {
        id: crypto.randomUUID(),
        type: "email",
        label: "Email",
        required: true,
        placeholder: "john@example.com",
      },
      {
        id: crypto.randomUUID(),
        type: "select",
        label: "Employment Status",
        required: true,
        options: [
          { label: "Employed", value: "employed" },
          { label: "Self-Employed", value: "self-employed" },
          { label: "Unemployed", value: "unemployed" },
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "number",
        label: "Loan Amount",
        required: true,
        placeholder: "10000",
      },
      {
        id: crypto.randomUUID(),
        type: "select",
        label: "Reason for Loan",
        required: true,
        options: [
          { label: "Business", value: "business" },
          { label: "Education", value: "education" },
          { label: "Home Purchase", value: "home" },
          { label: "Personal Use", value: "personal" },
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "textarea",
        label: "Additional Information",
        required: false,
        placeholder: "Provide any additional details...",
      },
    ],
  },
  {
    title: "Gym Membership Registration",
    id: crypto.randomUUID(),
    description: "Register for a gym membership with flexible plans.",
    category: "Membership Forms",
    tags: ["Fitness", "Gym", "Membership"],
    buttonText: "Join Now",
    formConfig: [
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Full Name",
        required: true,
        placeholder: "John Doe",
      },
      {
        id: crypto.randomUUID(),
        type: "email",
        label: "Email",
        required: true,
        placeholder: "john@example.com",
      },
      {
        id: crypto.randomUUID(),
        type: "number",
        label: "Age",
        required: true,
        placeholder: "25",
      },
      {
        id: crypto.randomUUID(),
        type: "select",
        label: "Membership Type",
        required: true,
        options: [
          { label: "Monthly", value: "monthly" },
          { label: "Quarterly", value: "quarterly" },
          { label: "Annual", value: "annual" },
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "radio-group",
        label: "Preferred Workout Time",
        required: true,
        options: [
          { label: "Morning", value: "morning" },
          { label: "Afternoon", value: "afternoon" },
          { label: "Evening", value: "evening" },
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "checkbox-group",
        label: "Fitness Goals",
        required: true,
        options: [
          { label: "Weight Loss", value: "weight-loss" },
          { label: "Muscle Gain", value: "muscle-gain" },
          { label: "General Fitness", value: "fitness" },
        ],
      },
    ],
  },
  {
    title: "Vendor Registration",
    id: crypto.randomUUID(),
    description: "Register your business as a vendor for partnerships.",
    category: "Business Registration Forms",
    tags: ["Vendor", "Business", "Registration"],
    buttonText: "Register Vendor",
    formConfig: [
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Business Name",
        required: true,
        placeholder: "ABC Enterprises",
      },
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Contact Person",
        required: true,
        placeholder: "John Doe",
      },
      {
        id: crypto.randomUUID(),
        type: "email",
        label: "Email",
        required: true,
        placeholder: "contact@abc.com",
      },
      {
        id: crypto.randomUUID(),
        type: "number",
        label: "Phone Number",
        required: true,
        placeholder: "1234567890",
      },
      {
        id: crypto.randomUUID(),
        type: "select",
        label: "Business Category",
        required: true,
        options: [
          { label: "Retail", value: "retail" },
          { label: "Wholesale", value: "wholesale" },
          { label: "Services", value: "services" },
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "number",
        label: "Years in Business",
        required: true,
        placeholder: "5",
      },
      {
        id: crypto.randomUUID(),
        type: "textarea",
        label: "Description of Business",
        required: true,
        placeholder: "Provide details about your business...",
      },
    ],
  },
  {
    title: "Dental Checkup",
    id: crypto.randomUUID(),
    description: "Book an appointment with a dentist for a routine checkup.",
    category: "Healthcare Forms",
    tags: ["Dental", "Checkup", "Appointment"],
    buttonText: "Schedule Checkup",
    formConfig: [
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Full Name",
        required: true,
        placeholder: "John Doe",
      },
      {
        id: crypto.randomUUID(),
        type: "email",
        label: "Email",
        required: true,
        placeholder: "john@example.com",
      },
      {
        id: crypto.randomUUID(),
        type: "number",
        label: "Phone Number",
        required: true,
        placeholder: "1234567890",
      },
      {
        id: crypto.randomUUID(),
        type: "date",
        label: "Preferred Date",
        required: true,
      },
      {
        id: crypto.randomUUID(),
        type: "select",
        label: "Dental Concern",
        required: true,
        options: [
          { label: "Routine Checkup", value: "routine" },
          { label: "Toothache", value: "toothache" },
          { label: "Gum Bleeding", value: "gum-bleeding" },
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "textarea",
        label: "Additional Notes",
        required: false,
        placeholder: "Provide any additional information...",
      },
    ],
  },
  {
    title: "Business Loan Request",
    id: crypto.randomUUID(),
    description: "Apply for a business loan with flexible repayment options.",
    category: "Financial Forms",
    tags: ["Loan", "Business", "Finance"],
    buttonText: "Request Loan",
    formConfig: [
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Business Name",
        required: true,
        placeholder: "ABC Enterprises",
      },
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Full Name",
        required: true,
        placeholder: "John Doe",
      },
      {
        id: crypto.randomUUID(),
        type: "email",
        label: "Email",
        required: true,
        placeholder: "contact@abc.com",
      },
      {
        id: crypto.randomUUID(),
        type: "number",
        label: "Requested Loan Amount",
        required: true,
        placeholder: "50000",
      },
      {
        id: crypto.randomUUID(),
        type: "select",
        label: "Purpose of Loan",
        required: true,
        options: [
          { label: "Expansion", value: "expansion" },
          { label: "Inventory Purchase", value: "inventory" },
          { label: "Equipment", value: "equipment" },
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "textarea",
        label: "Business Plan Summary",
        required: true,
        placeholder: "Briefly describe your business plan...",
      },
    ],
  },
 
  {
    title: "Fitness Class Enrollment",
    id: crypto.randomUUID(),
    description: "Sign up for a specialized fitness class at the gym.",
    category: "Membership Forms",
    tags: ["Fitness", "Gym", "Class"],
    buttonText: "Enroll Now",
    formConfig: [
      {
        id: crypto.randomUUID(),
        type: "text",
        label: "Full Name",
        required: true,
        placeholder: "John Doe",
      },
      {
        id: crypto.randomUUID(),
        type: "email",
        label: "Email",
        required: true,
        placeholder: "john@example.com",
      },
      {
        id: crypto.randomUUID(),
        type: "select",
        label: "Class Type",
        required: true,
        options: [
          { label: "Yoga", value: "yoga" },
          { label: "HIIT", value: "hiit" },
          { label: "Strength Training", value: "strength-training" },
        ],
      },
      {
        id: crypto.randomUUID(),
        type: "date",
        label: "Preferred Start Date",
        required: true,
      },
      {
        id: crypto.randomUUID(),
        type: "radio-group",
        label: "Preferred Time Slot",
        required: true,
        options: [
          { label: "Morning", value: "morning" },
          { label: "Evening", value: "evening" },
        ],
      },
    ],
  },
];

